# Generated by Django 3.1.7 on 2021-04-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=6)),
                ('response_time', models.PositiveSmallIntegerField()),
                ('datetime', models.DateTimeField()),
                ('shown_in_graph', models.BooleanField(default=False)),
            ],
        ),
    ]
